Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.hostname = "centosgeneric8"
  
    config.vm.network "forwarded_port", guest: 80, host: 8088
    config.vm.network "forwarded_port", guest: 81, host: 8081
    
    config.vm.synced_folder "./sites", "/var/www/html", type: "rsync",
    rsync__exclude: ".git/"

    config.vm.synced_folder ".", "/vagrant", disabled: true

  
    #added script for shell
    config.vm.provision "shell", path: "script.sh"
  
  
  end