FROM golang:1.16 as golang

RUN mkdir /wcg: \
    cd /wcg; \
    git clone https://github.com/Fenikks/world-cloud-generetor.git .; \
    make

CMD /wcg/artifacts/linux/world-cloud-generetor
#я знаю что она лишняя, но мне нравится)

FROM alpine:latest

RUN apk add gcompat
COPY --from=golang /wcg/artifacts/linux/word-cloud-generator .

CMD /word-cloud-generator