---
- name: instll Jenkins
  hosts: jenkins
  become: yes
  vars:
    jenkins_version: "2.221"
    jenkins_hostname: localhost
    jenkins_plugins:
      - golang
      - git
      - github
      - nexus-artifact-uploader
      - publish-over-ssh
      - Pipeline
      - ssh-agent
    jenkins_plugins_install_dependencies: true
    jenkins_folders:
      - dest: "{{ jenkins_home }}/jobs/BuildGo/"
      - dest: "{{ jenkins_home }}/.ssl/"
    jenkins_files:
      - name: "golang config"
        src: "/vagrant/roles/jenkins/templates/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml"
        dest: "{{ jenkins_home }}/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml"
      - name: "ssh-key"
        src: "/vagrant/roles/jenkins/templates/id_rsa"
        dest: "{{ jenkins_home }}/.ssl/id_rsa"
      - name: "publish-over-ssh config"
        src: "/vagrant/roles/jenkins/templates/jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml.j2"
        dest: "{{ jenkins_home }}/jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml"
      - name: "credentials plugin config"
        src: "/vagrant/roles/jenkins/templates/credentials.xml"
        dest: "{{ jenkins_home }}/credentials.xml"
      - name: "jenkins secrets master.key"
        src: "/vagrant/roles/jenkins/templates/master.key"
        dest: "{{ jenkins_home }}/secrets/master.key"
      - name: "jenkins secrets hudson.util.Secret"
        src: "/vagrant/roles/jenkins/templates/hudson.util.Secret"
        dest: "{{ jenkins_home }}/secrets/hudson.util.Secret"
      - name: "job BuildGo config"
        src: "/vagrant/roles/jenkins/templates/config.xml.j2"
        dest: "{{ jenkins_home }}/jobs/BuildGo/config.xml"
  pre_tasks:
    - apt:
        pkg:
        - mc
        - nano
        - git
        - build-essential
        - jq
        state: present
  roles:
    - role: "/etc/ansible/roles/jenkins"

- name: Setup Nexus
  hosts: nexus
  become: yes
  vars:
    java_packages:
      - adoptopenjdk-8-hotspot-jre
    nexus_admin_password: admin
    nexus_repos_raw_hosted:
      - name: word-cloud-generator
        write_policy: ALLOW
        blob_store: default
        strict_content_validation: false
    nexus_roles:
      - id: word-cloud-generator-developpers
        name: word-cloud-generator-developpers
        description: ''
        privileges:
          - nx-repository-view-raw-word-cloud-generator-*
        roles: []
      - id: word-cloud-generator-reader
        name: word-cloud-generator-reader
        description: ''
        privileges:
          - nx-repository-view-raw-word-cloud-generator-read
        roles: []
    nexus_local_users:
      - username: jenkins
        first_name: Jenkins
        last_name: CI
        email: support@company.com
        password: "{{ nexus_staging_production_password }}"
        roles:
          - word-cloud-generator-developpers
      - username: staging_production
        first_name: staging_production
        last_name: CI
        email: support@company.com
        password: "{{ nexus_staging_production_password }}"
        roles:
          - word-cloud-generator-reader
  pre_tasks:
    - apt:
        name: gpg
        state: present
    - apt_key:
        url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    - apt_repository:
        repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
        state: present
        update_cache: true
  roles:
    - role: "/etc/ansible/roles/java"
    - role: "/etc/ansible/roles/nexus3"

- name: Setup Word-Cloud-Generator
  hosts: staging_production
  become: yes
  roles:
    - role: "/etc/ansible/roles/java"
    - role: "/etc/ansible/roles/systemd-service"
      systemd_service:
        wordcloud:
          enabled: yes
          exec_start: "/opt/wordcloud/word-cloud-generator"
          wanted_by: "multi-user.target"
  tasks:
    - file:
        path: /opt/wordcloud/
        state: directory
        mode: '0755'
        owner: vagrant

    - apt:
        pkg: 
        - curl
        - git
        state: present
