Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
  
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
    end
  
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
  
    config.vm.provision :ansible_local do |ansible|
      ansible.playbook = 'playbook.yaml'
      ansible.inventory_path = "./inventory/hosts"
    end
  
    config.vm.define "master", primary: true do |master|
      master.vm.network "public_network", ip: "192.168.1.100"
      master.vm.hostname = "master.puppet"
    end  
  
    config.vm.define "slave1" do |slave1|
      slave1.vm.network "public_network", ip: "192.168.1.101"
      slave1.vm.hostname = "slave1.puppet"
    end  
  
    config.vm.define "slave2" do |slave2|
      slave2.vm.network "public_network", ip: "192.168.1.102"
      slave2.vm.hostname = "slave2.puppet"
    end  
  
  end