---
- name: "restart service"
  systemd:
    name: "{{ item.key }}.service"
    state: restarted
    daemon_reload: yes
  with_dict: "{{ systemd_service }}"
  when: systemd_restart_disabled | default(True)
