  Vagrant.configure("2") do |config|
  config.vm.box = "GenericNewLamp04042022"
  config.ssh.insert_key = false  
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "forwarded_port", guest: 80, host: 8088, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8087, host_ip: "127.0.0.1"

  config.vm.provision "shell", path: "script.sh"  

     config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yaml"
        ansible.become = true     
    end
  
  
end



