- name: Make dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: jenkins
    group: jenkins
  with_items:
      - /var/lib/jenkins/jobs/GoBuild

- name: Copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: jenkins
    group: jenkins
    force: yes
  with_items:
      - { src: "/temp/jobs/GoBuild/config.xml", dst: "/var/lib/jenkins/jobs/GoBuild/" }









#- name: create job
#   jenkins_job:
#     config: "{{ lookup('template', 'job-config-2.xml.j2') }}"
#     name: GoBuild
#     user: "{{ jenkins_user }}"
#     password: "{{ jenkins_password }}"