galaxy_info:
  author: Eugene Ignatov
  description: Create and configure a systemd service
  role_name: systemd_service
  company: Cimon.io
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
    - name: Ubuntu
      versions:
      - xenial
      - yakkety
      - zesty
      - artful
      - bionic
    - name: Debian
      versions:
      - stretch
      - jessie
      - buster
    - name: EL
      versions:
      - 7

  galaxy_tags:
    - service
    - system
    - systemd-service

dependencies: []
