$docker_install = <<-'SCRIPT'
sudo apt-get update && sudo apt-get upgarde
apt-get install docker.io docker-compose -y
# Docker without sudo
sudo gpasswd -a vagrant docker
newgrp docker
# Minicube install
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
sudo dpkg -i minikube_latest_amd64.deb
minikube start --driver=docker
alias k="minikube kubectl --"
# Terraform
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-get install software-properties-common
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update && sudo apt-get install terraform
sudo apt-get install unzip
wget https://releases.hashicorp.com/terraform/1.2.1/terraform_1.2.1_linux_amd64.zip
unzip terraform_1.2.1_linux_amd64.zip
sudo mv terraform /usr/local/bin/
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.hostname = "kubernets"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: $docker_install
 
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end

end