version: "3"

services:

  nexus:
    build: nexus/
    stdin_open: true
    networks:
      - lan        
    ports:
      - 81:8081
    container_name: jenkins

  jenkins:
    build: jenkins/
    stdin_open: true
    networks:
      - lan
    ports:
        - 80:8080
    container_name: nexus

networks:
    lan: