version: "3"

services:

  nexus:
    build: nexus/
    stdin_open: true
    networks:
      app_net:
        ipv4_address: 192.168.33.90
    ports:
      - 81:8081

  jenkins:
    build: jenkins/
    stdin_open: true
    networks:
      app_net:
        ipv4_address: 192.168.33.100
    ports:
      - 80:8080

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.33.0/24