---
 - hosts: servers
   become: true
   tasks:
     - name: Install jq
       apt:
         name: ['jq']
         state: latest
         update_cache: yes
     - name: Create folder
       file:
         path: /opt/wordcloud
         state: directory
         owner: vagrant
         group: vagrant
     - name: Copy service file 
       copy:  
         src: /vagrant/wordcloud.service
         dest:  /etc/systemd/system/wordcloud.service
     - name: SystemD_Reload
       ansible.builtin.systemd:
         daemon_reload: yes 
     - name: Enable Service wordcloud.service
       ansible.builtin.systemd:
         name: wordcloud.service
         enabled: yes