---
- name: Test play
  hosts: all

  tasks:

    - name: httpd
      become: yes
      yum: 
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - php
        
    - name: disable SElinux
      become: yes
      selinux:
        state: disabled

    - name: add static
      become: yes
      file:
        path: /etc/httpd/conf.d/01-demosite-static.conf
        state: touch

    - name: add php
      become: yes
      file:
        path: /etc/httpd/conf.d/01-demosite-php.conf
        state: touch

    - name: add conf static
      become: yes
      blockinfile:
        path: /etc/httpd/conf.d/01-demosite-static.conf
        block: |
          <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html/01-demosite-static
            DirectoryIndex index.html
          </VirtualHost>
    
    - name: add conf php
      become: yes
      blockinfile:
        path: /etc/httpd/conf.d/01-demosite-php.conf
        block: |
          <VirtualHost *:87>
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/html/01-demosite-php
            DirectoryIndex index.php
          </VirtualHost>
   
    - name: listen ports
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen'
        insertafter: '^#Listen'
        line: "Listen 8080\nListen 8087"

    - name: restart apache2
      systemd:
        name: httpd
        enabled: yes
        state: reloaded