Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.hostname = "teos-test03"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 87, host: 8087

  config.vm.provision "file", source: "./playbook.yaml", destination: "/vagrant/playbook.yaml"
  config.vm.synced_folder "../../sites", "/var/www/html", type: "rsync"
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = 'playbook.yaml'
    ansible.limit = 'all'
    ansible.verbose        = true
    ansible.install        = true
    ansible.become         = true
  end
end